# Generated by Django 6.0.7 on 2026-07-25 07:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('COE', 'Controller of Examinations'), ('ADMISSION', 'Admission Department'), ('ACCOUNTS', 'Accounts Department'), ('PLACEMENT', 'Placement Department'), ('STAFF', 'College Staff')], db_index=True, default='STAFF', help_text='Designated system access role.', max_length=20, verbose_name='System Role')),
                ('phone_number', models.CharField(blank=True, db_index=True, help_text='Contact mobile number (10 digits).', max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be a valid 10-digit Indian number, optionally prefixed with +91 or 91.', regex='^(?:\\+91|91)?[6789]\\d{9}$')], verbose_name='Phone Number')),
                ('employee_id', models.CharField(blank=True, db_index=True, help_text='Unique College Employee Identification Number.', max_length=50, null=True, unique=True, verbose_name='Employee / Staff ID')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Role Name')),
                ('code', models.CharField(choices=[('ADMIN', 'Administrator'), ('COE', 'Controller of Examinations'), ('ADMISSION', 'Admission Department'), ('ACCOUNTS', 'Accounts Department'), ('PLACEMENT', 'Placement Department'), ('STAFF', 'College Staff')], db_index=True, default='STAFF', max_length=30, unique=True, verbose_name='Role Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_system_role', models.BooleanField(default=False, verbose_name='Is System Built-in Role')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
    ]
