# Generated by Django 6.0.7 on 2026-07-25 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Associated college department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_roles', to='auth.permission', verbose_name='Assigned Permissions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role', verbose_name='RBAC Role Object'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_active'], name='idx_user_role_active'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['department', 'role'], name='idx_user_dept_role'),
        ),
    ]
