# Generated by Django 6.0.7 on 2026-07-28 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Created By Administrator'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, help_text='Staff job designation (e.g. Professor, HOD, Accountant).', max_length=100, verbose_name='Designation / Title'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Failed Login Attempts'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this user record is soft deleted.', verbose_name='Soft Deleted'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Prevents user from logging in when locked.', verbose_name='Account Locked'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Requires user to change password on next login.', verbose_name='Force Password Change'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Password Changed Date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='scope_type',
            field=models.CharField(choices=[('GLOBAL', 'Global (All Departments)'), ('DEPARTMENT', 'Department Only'), ('MULTI_DEPARTMENT', 'Multiple Departments')], default='GLOBAL', help_text='Controls data access boundaries across departments.', max_length=30, verbose_name='Data Access Scope'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('COE', 'Controller of Examinations'), ('ADMISSION', 'Admission Department'), ('ACCOUNTS', 'Accounts Department'), ('PLACEMENT', 'Placement Department'), ('LIBRARY', 'Library Department'), ('HOD', 'Head of Department'), ('STAFF', 'College Staff')], db_index=True, default='STAFF', help_text='Designated system access role.', max_length=20, verbose_name='System Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('COE', 'Controller of Examinations'), ('ADMISSION', 'Admission Department'), ('ACCOUNTS', 'Accounts Department'), ('PLACEMENT', 'Placement Department'), ('LIBRARY', 'Library Department'), ('HOD', 'Head of Department'), ('STAFF', 'College Staff')], db_index=True, default='STAFF', max_length=30, unique=True, verbose_name='Role Code'),
        ),
    ]
