# Generated by Django 6.0.7 on 2026-07-25 07:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('provider_name', models.CharField(default='Primary HTTP SMS Gateway', max_length=100, verbose_name='Provider Name')),
                ('api_url', models.URLField(help_text='HTTP SMS API Endpoint URL (e.g. http://api.sms-provider.com/send)', verbose_name='SMS Dispatch API URL')),
                ('balance_api_url', models.URLField(blank=True, help_text='Optional HTTP API endpoint to check remaining SMS credits.', verbose_name='Credit Balance API URL')),
                ('dlr_api_url', models.URLField(blank=True, help_text='Optional HTTP API endpoint to fetch status of dispatched SMS.', verbose_name='Delivery Report (DLR) API URL')),
                ('api_key', models.CharField(help_text='API Key or Auth Token required by SMS gateway provider.', max_length=255, verbose_name='API Key / Token')),
                ('username', models.CharField(blank=True, help_text='Account username if required by gateway HTTP authentication.', max_length=100, verbose_name='API Username')),
                ('password', models.CharField(blank=True, help_text='Account password if required by gateway HTTP authentication.', max_length=100, verbose_name='API Password')),
                ('default_sender_id', models.CharField(help_text='Approved 6-letter Header (e.g., CLGEXM).', max_length=10, validators=[django.core.validators.RegexValidator(message='Sender ID (Header) must consist of exactly 6 uppercase letters (e.g. CLGEXM).', regex='^[A-Z]{6}$')], verbose_name='Default Sender ID / Header')),
                ('default_entity_id', models.CharField(blank=True, help_text='DLT Registered Principal Entity ID.', max_length=50, validators=[django.core.validators.RegexValidator(message='DLT Template ID must be an 11 to 19 digit numerical string.', regex='^\\d{11,19}$')], verbose_name='Default Principal Entity ID')),
                ('request_method', models.CharField(choices=[('GET', 'HTTP GET'), ('POST', 'HTTP POST')], default='POST', max_length=10, verbose_name='HTTP Request Method')),
                ('http_headers', models.JSONField(blank=True, default=dict, help_text='JSON object of custom HTTP request headers (e.g. {"Authorization": "Bearer ..."})', verbose_name='Custom HTTP Headers')),
                ('param_mapping', models.JSONField(blank=True, default=dict, help_text='JSON key mapping (e.g. {"mobile": "number", "text": "msg", "template_id": "dlt_id"})', verbose_name='API Parameter Mapping JSON')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active Provider')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'SMS Gateway Config',
                'verbose_name_plural': 'SMS Gateway Configs',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
