# Generated by Django 6.0.7 on 2026-07-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(default='Default HTTP SMS API', max_length=100)),
                ('api_url', models.URLField(help_text='HTTP SMS API Endpoint URL')),
                ('api_key', models.CharField(help_text='API Authentication Key / Token', max_length=255)),
                ('default_sender_id', models.CharField(help_text='Approved Sender ID / Header', max_length=10)),
                ('entity_id', models.CharField(blank=True, help_text='Default DLT Principal Entity ID', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SMS Gateway Config',
                'verbose_name_plural': 'SMS Gateway Configs',
            },
        ),
    ]
