# Generated by Django 6.0.7 on 2026-07-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsgatewayconfig',
            name='response_format',
            field=models.CharField(blank=True, default='json', help_text='Expected API response format (json)', max_length=20, verbose_name='Response Format'),
        ),
        migrations.AddField(
            model_name='smsgatewayconfig',
            name='route_id',
            field=models.CharField(blank=True, default='1', help_text='SMS Provider Route ID (e.g. 1 for Transactional/DLT)', max_length=50, verbose_name='Route ID'),
        ),
    ]
