# Generated by Django 6.0.7 on 2026-07-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_smsgatewayconfig_response_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsgatewayconfig',
            name='timeout',
            field=models.PositiveIntegerField(default=10, help_text='HTTP request timeout limit in seconds.', verbose_name='Request Timeout (Seconds)'),
        ),
    ]
