# Generated by Django 6.0.7 on 2026-07-25 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='Full name of the department (e.g., Controller of Examinations)', max_length=100, unique=True, verbose_name='Department Name')),
                ('code', models.CharField(db_index=True, help_text='Unique short code in uppercase (e.g., COE, ADM, ACCTS, CSE)', max_length=20, unique=True, verbose_name='Department Code')),
                ('description', models.TextField(blank=True, help_text='Brief description of department responsibilities.', verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this department is active.', verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='idx_dept_code_active')],
            },
        ),
    ]
