# Generated by Django 6.0.7 on 2026-07-29 06:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='Full name of the recipient staff member.', max_length=100, verbose_name='Staff Name')),
                ('mobile_number', models.CharField(db_index=True, help_text='10-digit Indian Mobile Number for SMS delivery.', max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be a valid 10-digit Indian number, optionally prefixed with +91 or 91.', regex='^(?:\\+91|91)?[6789]\\d{9}$')], verbose_name='Mobile Number')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_recipients', to='users.department', verbose_name='Department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Staff Recipient',
                'verbose_name_plural': 'Staff Recipients',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'mobile_number'], name='idx_staff_name_mobile'), models.Index(fields=['department', 'is_active'], name='idx_staff_dept_active')],
            },
        ),
    ]
