# Generated by Django 6.0.7 on 2026-07-25 07:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dlt_templates', '0001_initial'),
        ('sms', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('mobile_number', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be a valid 10-digit Indian number, optionally prefixed with +91 or 91.', regex='^(?:\\+91|91)?[6789]\\d{9}$')], verbose_name='Mobile Number')),
                ('message_content', models.TextField(verbose_name='Dispatched SMS Text')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent to Gateway'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], db_index=True, max_length=20, verbose_name='Dispatch Status')),
                ('credit_units', models.PositiveIntegerField(default=1, verbose_name='SMS Credit Units')),
                ('gateway_message_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Gateway Transaction ID')),
                ('gateway_status_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gateway Return Status Code')),
                ('gateway_response_raw', models.TextField(blank=True, null=True, verbose_name='Raw HTTP Gateway Response')),
                ('dlr_status', models.CharField(blank=True, db_index=True, help_text='Delivery report status returned from SMS gateway (DELIVRD, REJECTD, UNDELIV, EXPIRED)', max_length=50, null=True, verbose_name='DLR Delivery Report Status')),
                ('dlr_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='DLR Delivery Timestamp')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='sms.smsbatch', verbose_name='Associated SMS Batch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='users.department', verbose_name='Department')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='dlt_templates.dlttemplate', verbose_name='DLT Template')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL, verbose_name='Dispatched By User')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'status'], name='idx_log_created_status'), models.Index(fields=['mobile_number', 'created_at'], name='idx_log_mobile_created'), models.Index(fields=['department', 'created_at'], name='idx_log_dept_created'), models.Index(fields=['gateway_message_id'], name='idx_log_gw_msg_id')],
            },
        ),
    ]
