# Generated by Django 6.0.7 on 2026-07-25 07:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dlt_templates', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('file_name', models.CharField(max_length=255, verbose_name='Uploaded File Name')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='bulk_uploads/%Y/%m/%d/', verbose_name='Saved Upload File')),
                ('total_records', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Total Records')),
                ('processed_records', models.PositiveIntegerField(default=0, verbose_name='Processed Records')),
                ('successful_count', models.PositiveIntegerField(default=0, verbose_name='Successful SMS Count')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Failed SMS Count')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent to Gateway'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Batch Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Dispatch Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dispatch Completed At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_batches', to='users.department', verbose_name='Department')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='dlt_templates.dlttemplate', verbose_name='DLT Template Used')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_batches', to=settings.AUTH_USER_MODEL, verbose_name='Dispatched By User')),
            ],
            options={
                'verbose_name': 'SMS Batch',
                'verbose_name_plural': 'SMS Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('mobile_number', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be a valid 10-digit Indian number, optionally prefixed with +91 or 91.', regex='^(?:\\+91|91)?[6789]\\d{9}$')], verbose_name='Recipient Mobile Number')),
                ('message_content', models.TextField(verbose_name='Interpolated SMS Content')),
                ('variable_data', models.JSONField(blank=True, default=dict, help_text='Key-value pair dictionary of template variables applied.', verbose_name='Template Variable Data')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent to Gateway'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Queue Status')),
                ('credit_units', models.PositiveIntegerField(default=1, verbose_name='SMS Credit Units Consumed')),
                ('gateway_message_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Gateway Message ID / Reference')),
                ('gateway_response_raw', models.TextField(blank=True, null=True, verbose_name='Raw Gateway API Response')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Dispatch Retry Attempts')),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Scheduled Dispatch Time')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='sms.smsbatch', verbose_name='Associated SMS Batch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_sms', to='users.department', verbose_name='Department')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queued_messages', to='dlt_templates.dlttemplate', verbose_name='DLT Template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queued_sms', to=settings.AUTH_USER_MODEL, verbose_name='Dispatched By User')),
            ],
            options={
                'verbose_name': 'SMS Queue Item',
                'verbose_name_plural': 'SMS Queue Items',
                'ordering': ['scheduled_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='smsbatch',
            index=models.Index(fields=['status', 'created_at'], name='idx_batch_status_created'),
        ),
        migrations.AddIndex(
            model_name='smsbatch',
            index=models.Index(fields=['user', 'created_at'], name='idx_batch_user_created'),
        ),
        migrations.AddIndex(
            model_name='smsqueue',
            index=models.Index(fields=['status', 'scheduled_at'], name='idx_queue_status_sched'),
        ),
        migrations.AddIndex(
            model_name='smsqueue',
            index=models.Index(fields=['mobile_number', 'status'], name='idx_queue_mobile_status'),
        ),
        migrations.AddIndex(
            model_name='smsqueue',
            index=models.Index(fields=['gateway_message_id'], name='idx_queue_gw_id'),
        ),
    ]
