# Generated by Django 6.0.7 on 2026-07-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DLTTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Human readable template name', max_length=150)),
                ('dlt_template_id', models.CharField(help_text='Registered DLT Content Template ID', max_length=50, unique=True)),
                ('entity_id', models.CharField(help_text='Registered DLT Principal Entity ID', max_length=50)),
                ('header_sender_id', models.CharField(help_text='Approved Sender ID Header (e.g. CLGEXM)', max_length=10)),
                ('template_content', models.TextField(help_text='DLT template text containing placeholders like {#var#}')),
                ('category', models.CharField(default='Service Implicit', help_text='Transactional, Service Implicit, etc.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'DLT Template',
                'verbose_name_plural': 'DLT Templates',
                'ordering': ['name'],
            },
        ),
    ]
