# Generated by Django 6.0.7 on 2026-07-25 07:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DLTTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='Human readable descriptive template title.', max_length=150, verbose_name='Template Name')),
                ('dlt_template_id', models.CharField(db_index=True, help_text='11 to 19 digit DLT registered content template ID.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='DLT Template ID must be an 11 to 19 digit numerical string.', regex='^\\d{11,19}$')], verbose_name='DLT Content Template ID')),
                ('entity_id', models.CharField(db_index=True, help_text='College DLT Registered Entity ID.', max_length=50, validators=[django.core.validators.RegexValidator(message='DLT Template ID must be an 11 to 19 digit numerical string.', regex='^\\d{11,19}$')], verbose_name='DLT Principal Entity ID')),
                ('header_sender_id', models.CharField(db_index=True, help_text='Approved 6-character Header/Sender ID (e.g., CLGEXM).', max_length=10, validators=[django.core.validators.RegexValidator(message='Sender ID (Header) must consist of exactly 6 uppercase letters (e.g. CLGEXM).', regex='^[A-Z]{6}$')], verbose_name='Sender ID (Header)')),
                ('template_content', models.TextField(help_text='Exact DLT approved template text. Use {#var#} or {#val#} for variables.', verbose_name='Template Content')),
                ('category', models.CharField(choices=[('SERVICE_IMPLICIT', 'Service Implicit (Transactional OTPs, Alerts)'), ('SERVICE_EXPLICIT', 'Service Explicit (Updates, Notices)'), ('TRANSACTIONAL', 'Transactional (Banking/OTP)'), ('PROMOTIONAL', 'Promotional')], db_index=True, default='SERVICE_IMPLICIT', max_length=30, verbose_name='Template Category')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('department', models.ForeignKey(blank=True, help_text='Restrict usage to specific department (leave empty for global access).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlt_templates', to='users.department', verbose_name='Associated Department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'DLT Template',
                'verbose_name_plural': 'DLT Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('position', models.PositiveIntegerField(help_text='Order of occurrence in template (1, 2, 3...)', verbose_name='Variable Position')),
                ('name', models.CharField(help_text='Descriptive variable identifier (e.g. student_name, exam_date, amount)', max_length=50, verbose_name='Variable Name')),
                ('sample_value', models.CharField(blank=True, help_text='Example value for preview rendering.', max_length=100, verbose_name='Sample Value')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='dlt_templates.dlttemplate', verbose_name='DLT Template')),
            ],
            options={
                'verbose_name': 'Template Variable',
                'verbose_name_plural': 'Template Variables',
                'ordering': ['template', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='dlttemplate',
            index=models.Index(fields=['dlt_template_id', 'is_active'], name='idx_tmpl_id_active'),
        ),
        migrations.AddIndex(
            model_name='dlttemplate',
            index=models.Index(fields=['category', 'is_active'], name='idx_tmpl_cat_active'),
        ),
        migrations.AddConstraint(
            model_name='templatevariable',
            constraint=models.UniqueConstraint(fields=('template', 'position'), name='unique_template_variable_position'),
        ),
    ]
