# Generated by Django 6.0.7 on 2026-08-01 01:36

import django.db.models.deletion
from django.db import migrations, models


def populate_allowed_offices(apps, schema_editor):
    DLTTemplate = apps.get_model('dlt_templates', 'DLTTemplate')
    for tmpl in DLTTemplate.objects.filter(department__isnull=False):
        tmpl.allowed_offices.add(tmpl.department)


class Migration(migrations.Migration):

    dependencies = [
        ('dlt_templates', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlttemplate',
            name='allowed_offices',
            field=models.ManyToManyField(blank=True, help_text='Offices permitted to view and use this template.', related_name='allowed_dlt_templates', to='users.department', verbose_name='Allowed Offices'),
        ),
        migrations.AlterField(
            model_name='dlttemplate',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Primary department/office template belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlt_templates', to='users.department', verbose_name='Primary Office'),
        ),
        migrations.RunPython(populate_allowed_offices, reverse_code=migrations.RunPython.noop),
    ]
